DROP TABLE IF EXISTS AIRLINES CASCADE;
CREATE TABLE AIRLINES
(
    ID           INTEGER            NOT NULL IDENTITY,
    AIRLINE      VARCHAR(50) UNIQUE NOT NULL,
    FLEET_SIZE   INTEGER            NOT NULL,
    DESTINATIONS INTEGER            NOT NULL,
    FLIGHTS      INTEGER
);

DROP TABLE IF EXISTS FLIGHTS CASCADE;
CREATE TABLE FLIGHTS
(
    ID            INTEGER            NOT NULL IDENTITY,
    AIRLINE       VARCHAR(50)        NOT NULL FOREIGN KEY REFERENCES AIRLINES(airline),
    FLIGHT_NUMBER VARCHAR(25) UNIQUE NOT NULL,
    FLIGHT_TYPE   VARCHAR(25)        NOT NULL,
    DEPARTURE     VARCHAR(50)        NOT NULL,
    ARRIVAL       VARCHAR(50)        NOT NULL,
    DATE          DATE               NOT NULL,
    ON_TIME       BOOLEAN            NOT NULL
);

DROP TABLE IF EXISTS PASSENGERS CASCADE;
CREATE TABLE PASSENGERS
(
    ID      INTEGER      NOT NULL IDENTITY,
    NAME    VARCHAR(100) NOT NULL,
    AGE     INTEGER      NOT NULL,
    GENDER  VARCHAR(20)  NOT NULL,
    TRANSIT BOOLEAN      NOT NULL,
    FLIGHTS INTEGER
);
/* WEEK-7 REQUIREMENT ENDS */

-- This part is not needed at the moment, come back later.
-- DROP TABLE IF EXISTS BOOKED_FLIGHTS CASCADE;
-- CREATE TABLE BOOKED_FLIGHTS(
--     FLIGHT_ID INTEGER FOREIGN KEY REFERENCES FLIGHTS(id),
--     PASSENGER_ID INTEGER FOREIGN KEY REFERENCES PASSENGERS(id)
-- );
